# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
include:
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: glove80_lh
    shield: settings_reset
  - board: glove80_rh
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: glove80_dongle
  - board: glove80_lh
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: glove80_rh
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
